spring.application.name=auctions

server.port=8443

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=AUCTIONS
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=auctions

spring.datasource.url=jdbc:mysql://localhost:3306/auctions_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Alex04P5
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jackson.date-format=yyyy-MM-dd'T'HH-mm-ssXXX
spring.jackson.time-zone=UTC